function renderCreateQuestion() {
  shell(`<section class="panel form-panel"><h1 class="section-title">나만의 문제 만들기</h1><p class="small-title">직무 지식을 문제로 정리하고, 다음 퀴즈에서 다시 풀어보세요.</p><form onsubmit="handleQuestionCreate(event)"><div class="form-grid"><div class="form-group"><label>분야</label><select name="domain" required onchange="updateCategoryOptions(this.value)"><option value="display">디스플레이</option><option value="semiconductor">반도체</option></select></div><div class="form-group"><label>직무 카테고리</label><select name="category" required>${categoryOptions()}</select></div><div class="form-group"><label>난이도</label><select name="difficulty"><option>입문</option><option>기초</option><option>중급</option><option>고급</option></select></div></div><div class="form-group"><label>문제</label><textarea name="question" required maxlength="300" placeholder="예: OLED 봉지 공정의 목적은 무엇인가요?"></textarea></div><div class="form-grid option-grid">${[0,1,2,3].map(i => `<div class="form-group"><label>보기 ${String.fromCharCode(65+i)}</label><input name="option${i}" required maxlength="100" /></div>`).join('')}</div><div class="form-group"><label>정답</label><select name="answer"><option value="0">보기 A</option><option value="1">보기 B</option><option value="2">보기 C</option><option value="3">보기 D</option></select></div><div class="form-group"><label>해설</label><textarea name="explanation" required maxlength="500" placeholder="정답인 이유와 면접에서 설명할 핵심을 적어주세요."></textarea></div><div class="row"><button class="primary-btn" type="submit">문제 저장</button><button class="ghost-btn" type="button" onclick="go('mypage')">취소</button></div></form></section>`, 'create');
}
function categoryOptions() { return Object.entries(DATA.display.categories).map(([key, category]) => `<option value="${key}">${category.label}</option>`).join(''); }
function updateCategoryOptions(domain) { const select = document.querySelector('select[name="category"]'); if (select) select.innerHTML = Object.entries(DATA[domain].categories).map(([key, category]) => `<option value="${key}">${category.label}</option>`).join(''); }
function handleQuestionCreate(event) {
  event.preventDefault();
  const form = new FormData(event.target); const user = getUser();
  const question = { id: Date.now(), domain: form.get('domain'), category: form.get('category'), difficulty: form.get('difficulty'), q: form.get('question'), options: [0,1,2,3].map(i => form.get(`option${i}`)), answer: Number(form.get('answer')), explanation: form.get('explanation'), author: user.name };
  saveCustomQuestions([question, ...getCustomQuestions()]);
  alert('문제가 저장되었습니다. 해당 카테고리 퀴즈에서 출제됩니다.'); goDomain(question.domain);
}

function renderCommunity() {
  // 게시글과 댓글을 같은 배열로 관리해 새로고침 후에도 유지합니다.
  const posts = getPosts();
  const cards = posts.length ? posts.map(post => `<article class="community-post"><div class="post-meta"><span class="badge">${escapeHtml(post.domain)}</span><span>${escapeHtml(post.author)} · ${escapeHtml(post.date)}</span></div><h3>${escapeHtml(post.title)}</h3><p>${escapeHtml(post.body)}</p><div class="post-footer"><span>💬 ${post.comments.length}개 댓글</span><button class="link-btn" onclick="toggleComments(${post.id})">댓글 보기/쓰기</button></div><div id="comments-${post.id}" class="comments" hidden>${post.comments.map(comment => `<p><strong>${escapeHtml(comment.author)}</strong> ${escapeHtml(comment.body)}</p>`).join('') || '<p class="empty">첫 번째 댓글을 남겨보세요.</p>'}<form onsubmit="handleComment(event, ${post.id})"><input name="body" required maxlength="200" placeholder="답변이나 지식을 공유해보세요" /><button class="primary-btn" type="submit">등록</button></form></div></article>`).join('') : '<div class="empty">아직 게시글이 없습니다. 첫 지식을 공유해보세요.</div>';
  shell(`<div class="grid two-col community-layout"><section><div class="community-heading"><div><h1 class="section-title">직무 커뮤니티</h1><p class="small-title">문제 풀이 팁, 면접 지식, 현업 정보를 서로 나눠보세요.</p></div><button class="primary-btn" onclick="requireLogin(renderPostForm)">글쓰기</button></div><div class="community-list">${cards}</div></section><aside class="panel community-guide"><h2 class="section-title">공유 주제</h2><div class="tags"><span class="tag">면접 답변</span><span class="tag">공정 지식</span><span class="tag">직무 경험</span><span class="tag">취업 정보</span></div><p>좋은 답변은 근거와 실제 공정 용어를 함께 담습니다.</p></aside></div>`, 'community');
}
function renderPostForm() { shell(`<section class="panel form-panel"><h1 class="section-title">지식 공유하기</h1><form onsubmit="handlePostCreate(event)"><div class="form-grid"><div class="form-group"><label>분야</label><select name="domain"><option>디스플레이</option><option>반도체</option><option>취업 일반</option></select></div><div class="form-group"><label>제목</label><input name="title" required maxlength="80" placeholder="공유하고 싶은 내용을 한 줄로 적어주세요" /></div></div><div class="form-group"><label>내용</label><textarea name="body" required maxlength="1000" placeholder="답변, 지식, 정보 또는 질문을 작성해주세요."></textarea></div><div class="row"><button class="primary-btn" type="submit">게시하기</button><button class="ghost-btn" type="button" onclick="go('community')">취소</button></div></form></section>`, 'community'); }
function handlePostCreate(event) { event.preventDefault(); const form = new FormData(event.target); const user = getUser(); savePosts([{ id: Date.now(), domain: form.get('domain'), title: form.get('title'), body: form.get('body'), author: user.name, date: new Date().toLocaleDateString('ko-KR'), comments: [] }, ...getPosts()]); go('community'); }
function toggleComments(id) { const comments = document.querySelector(`#comments-${id}`); if (comments) comments.hidden = !comments.hidden; }
function handleComment(event, postId) { event.preventDefault(); const form = new FormData(event.target); const posts = getPosts(); const post = posts.find(item => item.id === postId); if (!post) return; post.comments.push({ author: getUser().name, body: form.get('body') }); savePosts(posts); renderCommunity(); }
